/**
 * ECHTER FAHRZEUGBESTAND
 * ---------------------------------------------------------
 * Direkt von der echten mobile.de-Händlerseite abgerufen:
 * https://home.mobile.de/AUTOGALERIEKELES
 * Alle 37 aktuell inserierten Fahrzeuge, jeweils inkl. eines
 * echten Fotos aus dem mobile.de-Inserat (Stand: 04.07.2026).
 *
 * Das ist die EINZIGE Quelle für Fahrzeugdaten auf der ganzen
 * Website (Startseite-Highlights + /fahrzeuge greifen beide
 * hier drauf zu). Sobald der Admin-Bereich aktiv genutzt wird,
 * ersetzt der Blob-Store diese Datei 1:1 als Datenquelle — die
 * Struktur bleibt gleich, diese Datei bleibt der Fallback.
 *
 * Hinweise zur Datenqualität:
 * - Getriebe ("transmission") wird nur gesetzt, wenn es im
 *   mobile.de-Inserat explizit stand (z.B. "Autom." oder "DSG").
 *   Bei den übrigen Fahrzeugen ist es unbekannt und wird bewusst
 *   weggelassen statt geraten.
 * - Vorbesitzer ("owners") wird nur gesetzt, wenn im Inserat
 *   ausdrücklich "1. Hand" stand. Sonst weggelassen.
 * - Verbrauch/Emissionen waren in der Kompaktansicht nicht
 *   verfügbar und wurden bewusst nicht erfunden.
 * - Jedes Fahrzeug hat aktuell genau 1 echtes Foto (aus der
 *   mobile.de-Trefferliste). Weitere Fotos je Fahrzeug lassen
 *   sich über den Admin-Bereich ergänzen, sobald der Kunde sie
 *   liefert oder mobile.de-Galerien einzeln abgerufen werden.
 */

export type Vehicle = {
  id: number
  slug: string
  brand: string
  model: string
  detail: string
  description: string
  price: number
  priceNote?: string // z.B. "MwSt. ausweisbar"
  firstRegistration: string // MM/JJJJ
  km: number
  powerKw: number
  powerPs: number
  fuel: 'Benzin' | 'Diesel' | 'Hybrid' | 'Elektro'
  transmission?: 'Automatik' | 'Schaltgetriebe'
  owners?: number
  consumption?: string
  emissions?: string
  featured: boolean
  photos: string[] // leer = noch kein echtes Foto vorhanden
}

export const vehicles: Vehicle[] = [
  {
    id: 1,
    slug: 'vw-golf-vii-r-4motion-behindertenumbau',
    brand: 'Volkswagen',
    model: 'Golf VII R 4MOTION',
    detail: 'Allradantrieb (4MOTION) · Behindertengerechter Umbau · Handgas',
    description: 'Unfallfreier Volkswagen Golf VII R mit 4MOTION-Allradantrieb und 381 PS. Mit behindertengerechtem Umbau (Handgas) für eingeschränkte Mobilität ausgestattet – ein seltenes, leistungsstarkes Sondermodell.',
    price: 27951,
    firstRegistration: '11/2017',
    km: 134000,
    powerKw: 280,
    powerPs: 381,
    fuel: 'Benzin',
    featured: false,
    photos: ['/api/vehicle-image/5b/5b6fe3c1-77a4-4bf7-8921-a605b98f55e7'],
  },
  {
    id: 2,
    slug: 'vw-touran-join-automatik-7-sitzer',
    brand: 'Volkswagen',
    model: 'Touran Join',
    detail: 'Automatikgetriebe · 7 Sitze · Navigationssystem · Kamera · Anhängerkupplung',
    description: 'Volkswagen Touran Join mit Automatikgetriebe, 7 Sitzen, Navigationssystem, Kamera und Anhängerkupplung – der ideale Familienwagen mit viel Platz und Komfort.',
    price: 19861,
    firstRegistration: '01/2019',
    km: 120000,
    powerKw: 110,
    powerPs: 150,
    fuel: 'Benzin',
    transmission: 'Automatik',
    featured: false,
    photos: ['/api/vehicle-image/a9/a96910cb-f43a-4551-9b4b-4c185da4ea45'],
  },
  {
    id: 3,
    slug: 'mercedes-45-amg-4matic',
    brand: 'Mercedes-Benz',
    model: '45 AMG 4MATIC',
    detail: 'Allradantrieb (4MATIC) · Memory-Sitze · Panoramadach · Rückfahrkamera · Lederausstattung · Totwinkelassistent',
    description: 'Mercedes-Benz 45 AMG mit 4MATIC-Allradantrieb, Memory-Sitzen, Panoramadach, Rückfahrkamera, Lederausstattung und Totwinkelassistent – kompromissloser AMG-Antrieb mit 381 PS.',
    price: 27951,
    firstRegistration: '12/2017',
    km: 125000,
    powerKw: 280,
    powerPs: 381,
    fuel: 'Benzin',
    featured: false,
    photos: ['/api/vehicle-image/d3/d37d3d25-e9bb-4b2e-8341-958a6bb9c20b'],
  },
  {
    id: 4,
    slug: 'vw-arteon-elegance',
    brand: 'Volkswagen',
    model: 'Arteon Elegance',
    detail: 'Panoramadach · Kamera · Digitales Kombiinstrument · Anhängerkupplung · Spurhalteassistent',
    description: 'Unfallfreier Volkswagen Arteon Elegance mit Panoramadach, Kamera, digitalem Kombiinstrument, Anhängerkupplung und Spurhalteassistent – elegantes Design trifft auf modernste Assistenzsysteme.',
    price: 25951,
    firstRegistration: '12/2020',
    km: 100000,
    powerKw: 140,
    powerPs: 190,
    fuel: 'Benzin',
    featured: false,
    photos: ['/api/vehicle-image/9b/9bbdc9d4-9fa4-40dd-81ec-bd713acbae08'],
  },
  {
    id: 5,
    slug: 'vw-tiguan-highline-4x4',
    brand: 'Volkswagen',
    model: 'Tiguan Highline 4X4',
    detail: 'Allradantrieb (4X4) · Digitales Kombiinstrument · Navigationssystem · Xenonlicht · Anhängerkupplung',
    description: 'Volkswagen Tiguan Highline mit 4X4-Allradantrieb, digitalem Kombiinstrument, Navigationssystem, Xenonlicht und Anhängerkupplung – souverän auf jedem Untergrund.',
    price: 23751,
    firstRegistration: '12/2019',
    km: 108000,
    powerKw: 140,
    powerPs: 190,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/31/31ed5f2e-3d5d-4c3e-8e24-cd1405f76269'],
  },
  {
    id: 6,
    slug: 'ford-edge-sport-4x4',
    brand: 'Ford',
    model: 'Edge Sport 4x4',
    detail: 'Allradantrieb · Lederausstattung · Panoramadach · Spurhalteassistent · Kamera · Totwinkelassistent',
    description: 'Ford Edge Sport mit Allradantrieb, Lederausstattung, Panoramadach, Spurhalteassistent, Kamera und Totwinkelassistent – ein kraftvolles SUV mit vollem Ausstattungspaket.',
    price: 17951,
    firstRegistration: '07/2016',
    km: 100000,
    powerKw: 155,
    powerPs: 211,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/d1/d170eba0-b1e4-489b-ac76-e54473a08260'],
  },
  {
    id: 7,
    slug: 'vw-golf-viii-move-automatik-digital',
    brand: 'Volkswagen',
    model: 'Golf VIII Limousine Move',
    detail: 'Automatikgetriebe · Digitales Kombiinstrument · Kamera · LED-Scheinwerfer · Adaptiver Tempomat',
    description: 'Volkswagen Golf VIII Move mit Automatikgetriebe, digitalem Kombiinstrument, Kamera, LED-Scheinwerfern und adaptivem Tempomat – junger, sparsamer Diesel mit moderner Ausstattung.',
    price: 23351,
    firstRegistration: '07/2023',
    km: 92000,
    powerKw: 110,
    powerPs: 150,
    fuel: 'Diesel',
    transmission: 'Automatik',
    featured: false,
    photos: ['/api/vehicle-image/85/852d30c1-6ced-4087-a17d-bfa932d2f4cd'],
  },
  {
    id: 8,
    slug: 'vw-golf-viii-move-automatik-ahk',
    brand: 'Volkswagen',
    model: 'Golf VIII Limousine Move',
    detail: 'Automatikgetriebe · Kamera · LED-Scheinwerfer · Adaptiver Tempomat · Anhängerkupplung',
    description: 'Volkswagen Golf VIII Move mit Automatikgetriebe, Kamera, LED-Scheinwerfern, adaptivem Tempomat und Anhängerkupplung – ebenfalls jung und sparsam, dafür mit Anhängerkupplung statt Digitaltacho.',
    price: 22741,
    firstRegistration: '07/2023',
    km: 87000,
    powerKw: 110,
    powerPs: 150,
    fuel: 'Diesel',
    transmission: 'Automatik',
    featured: false,
    photos: ['/api/vehicle-image/69/69ff19ed-b5c9-46ac-bb9c-05070e6f3bf7'],
  },
  {
    id: 9,
    slug: 'vw-new-beetle-cabriolet-1-6',
    brand: 'Volkswagen',
    model: 'New Beetle Cabriolet 1.6',
    detail: 'Klimaanlage · Sitzheizung · Einparkhilfe',
    description: 'Volkswagen New Beetle Cabriolet 1.6 mit Klimaanlage, Sitzheizung und Einparkhilfe – der Kult-Cabrio-Klassiker für die sonnigen Tage.',
    price: 6951,
    firstRegistration: '07/2010',
    km: 124000,
    powerKw: 75,
    powerPs: 102,
    fuel: 'Benzin',
    featured: false,
    photos: ['/api/vehicle-image/94/940c38ec-c6ca-427f-9d59-9a36c88a7c66'],
  },
  {
    id: 10,
    slug: 'vw-polo-v-comfortline',
    brand: 'Volkswagen',
    model: 'Polo V Comfortline',
    detail: 'Klimaanlage · Einparkhilfe · Euro 6 · Funkfernbedienung',
    description: 'Volkswagen Polo V Comfortline mit Klimaanlage, Einparkhilfe, Euro-6-Norm und Funkfernbedienung – der zuverlässige und günstige Stadtflitzer.',
    price: 6951,
    firstRegistration: '10/2014',
    km: 144000,
    powerKw: 44,
    powerPs: 60,
    fuel: 'Benzin',
    featured: false,
    photos: ['/api/vehicle-image/06/067b82d2-aca4-445b-87d5-76aec1be44a0'],
  },
  {
    id: 11,
    slug: 'mercedes-vito-kasten-fwd-lang',
    brand: 'Mercedes-Benz',
    model: 'Vito Kasten 109/110/111/114 CDI FWD lang',
    detail: 'Klimaanlage · Langer Radstand · Frontantrieb',
    description: 'Mercedes-Benz Vito Kasten CDI mit Frontantrieb, langem Radstand und Klimaanlage – der solide Transporter für Handwerk und Gewerbe.',
    price: 11861,
    firstRegistration: '03/2017',
    km: 150000,
    powerKw: 84,
    powerPs: 114,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/65/651d1cb2-4603-4c48-b18b-4c16d25d3a4a'],
  },
  {
    id: 12,
    slug: 'audi-a4-avant-40-tdi-s-line',
    brand: 'Audi',
    model: 'A4 Avant 40 TDI S line',
    detail: 'Digitales Kombiinstrument · Anhängerkupplung · Rückfahrkamera · Sitzheizung',
    description: 'Audi A4 Avant 40 TDI S line mit digitalem Kombiinstrument, Anhängerkupplung, Rückfahrkamera und Sitzheizung – sportliches S-line-Design mit aktuellem Diesel-Antrieb.',
    price: 26841,
    priceNote: 'MwSt. ausweisbar',
    firstRegistration: '01/2023',
    km: 111000,
    powerKw: 150,
    powerPs: 204,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/13/13cee006-3ac3-4bc5-8744-60715d8d9be0'],
  },
  {
    id: 13,
    slug: 'vw-touran-sound-dsg',
    brand: 'Volkswagen',
    model: 'Touran Sound BMT/Start-Stopp',
    detail: 'DSG-Automatikgetriebe · Start-Stopp-System · Tempomat · Navigationssystem',
    description: 'Volkswagen Touran Sound mit DSG-Automatikgetriebe, Start-Stopp-System, Tempomat und Navigationssystem – komfortabler Familienvan mit Doppelkupplungsgetriebe.',
    price: 15351,
    firstRegistration: '12/2017',
    km: 163000,
    powerKw: 85,
    powerPs: 116,
    fuel: 'Diesel',
    transmission: 'Automatik',
    featured: false,
    photos: ['/api/vehicle-image/b0/b0b32f38-c2ed-4057-8f27-4751cc93c702'],
  },
  {
    id: 14,
    slug: 'vw-passat-comfortline-dsg',
    brand: 'Volkswagen',
    model: 'Passat Limousine Comfortline',
    detail: 'DSG-Automatikgetriebe · Klimaanlage · Einparkhilfe · Tempomat',
    description: 'Volkswagen Passat Comfortline mit DSG-Automatikgetriebe, Klimaanlage, Einparkhilfe und Tempomat – die bewährte Business-Limousine zum fairen Preis.',
    price: 9321,
    firstRegistration: '09/2013',
    km: 175000,
    powerKw: 155,
    powerPs: 211,
    fuel: 'Benzin',
    transmission: 'Automatik',
    featured: false,
    photos: ['/api/vehicle-image/33/3319cab4-fa3c-4d30-ba3c-2bbdae6fda89'],
  },
  {
    id: 15,
    slug: 'vw-touran-comfortline-euro5',
    brand: 'Volkswagen',
    model: 'Touran Comfortline',
    detail: 'Sitzheizung · Einparkhilfe · Tempomat · Euro 5',
    description: 'Volkswagen Touran Comfortline mit Sitzheizung, Einparkhilfe, Tempomat und Euro-5-Norm – ein günstiger und praktischer Familienvan.',
    price: 7651,
    firstRegistration: '11/2011',
    km: 166000,
    powerKw: 77,
    powerPs: 105,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/5c/5c526ef8-5195-46a4-b8c6-07a76a8e8123'],
  },
  {
    id: 16,
    slug: 'opel-zafira-c-tourer-edition',
    brand: 'Opel',
    model: 'Zafira C Tourer Edition',
    detail: 'Xenonlicht · Einparkhilfe · 7 Sitze · Totwinkelassistent',
    description: 'Opel Zafira C Tourer Edition mit Xenonlicht, Einparkhilfe, 7 Sitzen und Totwinkelassistent – geräumiger Van für die ganze Familie.',
    price: 10951,
    firstRegistration: '06/2016',
    km: 142000,
    powerKw: 125,
    powerPs: 170,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/73/7340145d-76d0-4133-bd0a-2226f6794fd7'],
  },
  {
    id: 17,
    slug: 'maserati-ghibli',
    brand: 'Maserati',
    model: 'Ghibli',
    detail: 'Lederausstattung · Navigationssystem · Xenonlicht · Memory-Sitze · Sportauspuffanlage',
    description: 'Maserati Ghibli mit Lederausstattung, Navigationssystem, Xenonlicht, Memory-Sitzen und Sportauspuffanlage – italienischer Sportlimousinen-Charakter mit unverwechselbarem Sound.',
    price: 25998,
    firstRegistration: '06/2017',
    km: 160000,
    powerKw: 210,
    powerPs: 286,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/e7/e755f1bd-73b2-4e5d-b914-f36aec4ff5ea'],
  },
  {
    id: 18,
    slug: 'volvo-xc90-inscription-awd',
    brand: 'Volvo',
    model: 'XC90 Inscription AWD',
    detail: 'Allradantrieb (AWD) · Spurhalteassistent · Navigationssystem · LED-Scheinwerfer · Memory-Sitze',
    description: 'Volvo XC90 Inscription mit AWD-Allradantrieb, Spurhalteassistent, Navigationssystem, LED-Scheinwerfern und Memory-Sitzen – skandinavisches Premium-SUV der Spitzenklasse.',
    price: 31381,
    firstRegistration: '12/2018',
    km: 141000,
    powerKw: 173,
    powerPs: 235,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/c8/c87616db-55b6-4fd7-8b96-a1fbbed10d3d'],
  },
  {
    id: 19,
    slug: 'citroen-c3-aircross-shine',
    brand: 'Citroën',
    model: 'C3 Aircross Shine',
    detail: 'Lederausstattung · Panoramadach · Kamera · Head-up-Display · Spurhalteassistent',
    description: 'Citroën C3 Aircross Shine mit Lederausstattung, Panoramadach, Kamera, Head-up-Display und Spurhalteassistent – kompaktes SUV mit viel Ausstattung für wenig Geld.',
    price: 9751,
    firstRegistration: '08/2018',
    km: 141000,
    powerKw: 96,
    powerPs: 131,
    fuel: 'Benzin',
    featured: false,
    photos: ['/api/vehicle-image/89/899308f9-6d14-4a84-9506-74a5e1fe1e5f'],
  },
  {
    id: 20,
    slug: 'audi-a8-3-0-tdi-quattro-design-selection',
    brand: 'Audi',
    model: 'A8 3.0 TDI quattro design Selection',
    detail: 'Allradantrieb (quattro) · Head-up-Display · 360°-Kamera',
    description: 'Audi A8 3.0 TDI quattro design Selection mit Allradantrieb, Head-up-Display und 360°-Kamera – die große Luxuslimousine mit souveränem Auftritt.',
    price: 21951,
    firstRegistration: '09/2015',
    km: 190000,
    powerKw: 190,
    powerPs: 258,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/e8/e85df878-2e0a-49c2-ba46-8ed0719103af'],
  },
  {
    id: 21,
    slug: 'ford-transit-custom-mixto-340-l2-trend',
    brand: 'Ford',
    model: 'Transit Custom MIXTO 340 L2 Trend',
    detail: 'Klimaanlage · Einparkhilfe',
    description: 'Ford Transit Custom MIXTO 340 L2 Trend mit Klimaanlage und Einparkhilfe – der vielseitige Kombi-Transporter für Gewerbe und Familie.',
    price: 15951,
    firstRegistration: '11/2019',
    km: 150000,
    powerKw: 96,
    powerPs: 131,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/c0/c0ef87e0-ac3f-4585-9298-c1328892838f'],
  },
  {
    id: 22,
    slug: 'iveco-daily-is35s12aa-pritsche-extralang',
    brand: 'Iveco',
    model: 'Daily IS35S12AA Pritsche Extralang',
    detail: 'Klimaanlage · Extralange Pritsche',
    description: 'Iveco Daily Pritsche Extralang mit Klimaanlage – das robuste Nutzfahrzeug mit maximaler Ladefläche für Handwerk und Transport.',
    price: 9951,
    firstRegistration: '08/2013',
    km: 150000,
    powerKw: 93,
    powerPs: 126,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/a2/a2995cd3-e3c7-4af4-85b7-51127261f150'],
  },
  {
    id: 23,
    slug: 'opel-zafira-on-7-sitzer',
    brand: 'Opel',
    model: 'Zafira ON',
    detail: '7 Sitze · Navigationssystem · Tempomat · Sitzheizung · Lenkradheizung',
    description: 'Opel Zafira ON mit 7 Sitzen, Navigationssystem, Tempomat, Sitzheizung und Lenkradheizung – geräumig, gut ausgestattet und familientauglich.',
    price: 10451,
    firstRegistration: '12/2018',
    km: 135000,
    powerKw: 88,
    powerPs: 120,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/29/299b72b5-0444-4f40-8b80-8bb96dcf018f'],
  },
  {
    id: 24,
    slug: 'audi-sq7-4-0-tdi-quattro',
    brand: 'Audi',
    model: 'SQ7 4.0 TDI quattro',
    detail: 'Allradantrieb (quattro) · Standheizung · Spurhalteassistent · Soft-Close-Türen · Virtual Cockpit',
    description: 'Audi SQ7 4.0 TDI quattro mit Standheizung, Spurhalteassistent, Soft-Close-Türen und Virtual Cockpit – 435 PS starkes Performance-SUV mit Achtzylinder-Diesel.',
    price: 38861,
    firstRegistration: '11/2017',
    km: 161000,
    powerKw: 320,
    powerPs: 435,
    fuel: 'Diesel',
    featured: true,
    photos: ['/api/vehicle-image/22/221c8033-81a6-460b-93f7-92d6636ab6fe'],
  },
  {
    id: 25,
    slug: 'mercedes-s-350-amg-line',
    brand: 'Mercedes-Benz',
    model: 'S 350',
    detail: 'LED-Scheinwerfer · Panoramadach · Memory-Sitze · Adaptiver Tempomat · AMG-Line',
    description: 'Mercedes-Benz S 350 AMG-Line mit LED-Scheinwerfern, Panoramadach, Memory-Sitzen und adaptivem Tempomat – die S-Klasse als Statement für Komfort und Understatement.',
    price: 24951,
    firstRegistration: '11/2013',
    km: 215000,
    powerKw: 190,
    powerPs: 258,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/70/707a9da2-0e4e-4c31-af8c-2f05921f1701'],
  },
  {
    id: 26,
    slug: 'mazda-cx-3-sports-line',
    brand: 'Mazda',
    model: 'CX-3 Sports-Line',
    detail: 'Lederausstattung · Navigationssystem · Xenonlicht · Head-up-Display · Spurhalteassistent · Kamera · Totwinkelassistent',
    description: 'Unfallfreier Mazda CX-3 Sports-Line mit Lederausstattung, Navigationssystem, Xenonlicht, Head-up-Display, Spurhalte- und Totwinkelassistent – kompaktes SUV mit außergewöhnlich niedrigem Kilometerstand.',
    price: 18651,
    firstRegistration: '02/2019',
    km: 9500,
    powerKw: 89,
    powerPs: 121,
    fuel: 'Benzin',
    featured: false,
    photos: ['/api/vehicle-image/80/8070b72a-c280-4a9f-a7e4-6f6a400620e6'],
  },
  {
    id: 27,
    slug: 'citroen-berlingo-feel-pack-m',
    brand: 'Citroën',
    model: 'Berlingo Feel Pack M',
    detail: 'Kamera · Spurhalteassistent · Totwinkelassistent · Navigationssystem',
    description: 'Citroën Berlingo Feel Pack mit Kamera, Spurhalteassistent, Totwinkelassistent und Navigationssystem – der vielseitige Familien- und Lastenesel mit moderner Assistenz.',
    price: 10951,
    firstRegistration: '05/2020',
    km: 150000,
    powerKw: 75,
    powerPs: 102,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/3f/3fa0d3c0-3ebe-4c9f-b23e-c123cb07363f'],
  },
  {
    id: 28,
    slug: 'mercedes-s63-amg-coupe-4matic',
    brand: 'Mercedes-Benz',
    model: 'S 63 AMG Coupe 4MATIC',
    detail: 'Allradantrieb (4MATIC) · Panoramadach · Head-up-Display · Sitzbelüftung · Spurhalteassistent · Keyless-Go',
    description: 'Mercedes-Benz S 63 AMG Coupe 4MATIC mit Panoramadach, Head-up-Display, Sitzbelüftung, Spurhalteassistent und Keyless-Go – 585 PS pure AMG-Faszination im Flaggschiff-Coupé.',
    price: 58751,
    firstRegistration: '12/2014',
    km: 110000,
    powerKw: 430,
    powerPs: 585,
    fuel: 'Benzin',
    featured: true,
    photos: ['/api/vehicle-image/37/37f63b67-e6d6-4cf3-9c23-b3b5de1c1022'],
  },
  {
    id: 29,
    slug: 'mercedes-c63-amg-carbon',
    brand: 'Mercedes-Benz',
    model: 'C 63 AMG',
    detail: 'Carbon-Zierteile · Panoramadach · Head-up-Display · Sportschalensitze',
    description: 'Mercedes-Benz C 63 AMG mit Carbon-Zierteilen, Panoramadach, Head-up-Display und Sportschalensitzen – 476 PS geballte AMG-Power im kompakten Format.',
    price: 52851,
    firstRegistration: '01/2020',
    km: 95000,
    powerKw: 350,
    powerPs: 476,
    fuel: 'Benzin',
    featured: true,
    photos: ['/api/vehicle-image/be/be343cf2-1d79-4cad-93f8-6a298b3cc504'],
  },
  {
    id: 30,
    slug: 'peugeot-partner-l1-premium',
    brand: 'Peugeot',
    model: 'Partner L1 Premium',
    detail: 'Elektrische Fensterheber · Einparkhilfe · Euro 6',
    description: 'Peugeot Partner L1 Premium mit elektrischen Fensterhebern, Einparkhilfe und Euro-6-Norm – kompakter und sparsamer Nutzfahrzeug-Allrounder.',
    price: 6451,
    priceNote: 'MwSt. ausweisbar',
    firstRegistration: '05/2017',
    km: 160000,
    powerKw: 55,
    powerPs: 75,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/00/00ba5048-bdbf-4e65-ac43-f354c70955b2'],
  },
  {
    id: 31,
    slug: 'ford-kuga-titanium',
    brand: 'Ford',
    model: 'Kuga Titanium',
    detail: 'Anhängerkupplung · Xenonlicht · Spurhalteassistent · Klimaanlage · Navigationssystem',
    description: 'Ford Kuga Titanium mit Anhängerkupplung, Xenonlicht, Spurhalteassistent, Klimaanlage und Navigationssystem – das bewährte Kompakt-SUV mit starkem Diesel.',
    price: 9951,
    firstRegistration: '12/2016',
    km: 183000,
    powerKw: 132,
    powerPs: 179,
    fuel: 'Diesel',
    featured: false,
    photos: ['/api/vehicle-image/bf/bf93cd85-766f-4407-a8b9-33893a081725'],
  },
  {
    id: 32,
    slug: 'kia-xceed-spirit-plug-in-hybrid',
    brand: 'Kia',
    model: 'XCeed Spirit Plug-in Hybrid',
    detail: 'Plug-in-Hybrid · Sitzheizung · LED-Scheinwerfer · Tempomat · Spurhalteassistent',
    description: 'Kia XCeed Spirit Plug-in Hybrid mit Sitzheizung, LED-Scheinwerfern, Tempomat und Spurhalteassistent – elektrisch fahren mit der Reichweitensicherheit eines Benziners.',
    price: 16841,
    firstRegistration: '12/2021',
    km: 58000,
    powerKw: 77,
    powerPs: 105,
    fuel: 'Hybrid',
    featured: false,
    photos: ['/api/vehicle-image/7a/7a5d95fa-d66e-4175-89fd-7bc1a609e92e'],
  },
  {
    id: 33,
    slug: 'mercedes-gle-350-d-4matic-amg',
    brand: 'Mercedes-Benz',
    model: 'GLE 350 d 4MATIC AMG',
    detail: 'Allradantrieb (4MATIC) · Panoramadach · 360°-Kamera · Head-up-Display · AMG-Line',
    description: 'Mercedes-Benz GLE 350 d 4MATIC AMG-Line mit Panoramadach, 360°-Kamera und Head-up-Display – das Premium-SUV mit AMG-Optik und satten 272 PS.',
    price: 50761,
    firstRegistration: '05/2020',
    km: 122000,
    powerKw: 200,
    powerPs: 272,
    fuel: 'Diesel',
    featured: true,
    photos: ['/api/vehicle-image/29/29a0c0a7-0c45-48d9-8c58-fcd7d349d041'],
  },
  {
    id: 34,
    slug: 'skoda-octavia-soleil-1-hand',
    brand: 'Skoda',
    model: 'Octavia Soleil',
    detail: '1. Hand · Sitzheizung · Adaptiver Tempomat · Lenkradheizung · Anhängerkupplung',
    description: 'Skoda Octavia Soleil aus erster Hand mit Sitzheizung, adaptivem Tempomat, Lenkradheizung und Anhängerkupplung – lückenlos nachvollziehbare Historie und viel Komfort.',
    price: 12851,
    firstRegistration: '12/2020',
    km: 185000,
    powerKw: 110,
    powerPs: 150,
    fuel: 'Diesel',
    owners: 1,
    featured: false,
    photos: ['/api/vehicle-image/f9/f97d3b18-c43a-4bfb-8481-3c7f605e5d8f'],
  },
  {
    id: 35,
    slug: 'ford-mondeo-turnier-business-edition-automatik',
    brand: 'Ford',
    model: 'Mondeo Turnier Business Edition',
    detail: 'Automatikgetriebe · Navigationssystem · Sitzheizung',
    description: 'Ford Mondeo Turnier Business Edition mit Automatikgetriebe, Navigationssystem und Sitzheizung – der geräumige Kombi für vielfahrende Business-Kunden.',
    price: 8651,
    firstRegistration: '02/2017',
    km: 214000,
    powerKw: 110,
    powerPs: 150,
    fuel: 'Diesel',
    transmission: 'Automatik',
    featured: false,
    photos: ['/api/vehicle-image/ff/ffa98839-99d0-40ec-9d5a-99d944d85633'],
  },
  {
    id: 36,
    slug: 'jaguar-f-type-coupe-r-dynamic-awd',
    brand: 'Jaguar',
    model: 'F-Type Coupe R-Dynamic AWD',
    detail: 'Allradantrieb (AWD) · Sportauspuffanlage · Jaguar Approved-Gebrauchtwagengarantie',
    description: 'Unfallfreies Jaguar F-Type Coupe R-Dynamic mit AWD-Allradantrieb, Sportauspuffanlage und Jaguar-Approved-Gebrauchtwagengarantie – 381 PS puristischer Sportwagen-Sound.',
    price: 51951,
    firstRegistration: '12/2020',
    km: 51000,
    powerKw: 280,
    powerPs: 381,
    fuel: 'Benzin',
    featured: true,
    photos: ['/api/vehicle-image/93/932084bf-934f-4c6d-8b08-076af4b2e0a3'],
  },
  {
    id: 37,
    slug: 'bmw-420d-coupe',
    brand: 'BMW',
    model: '420d Coupe',
    detail: 'LED-Scheinwerfer · Navigationssystem · Kamera · Spurhalteassistent · Sitzheizung · Tempomat',
    description: 'BMW 420d Coupe mit LED-Scheinwerfern, Navigationssystem, Kamera, Spurhalteassistent, Sitzheizung und Tempomat – eines der jüngsten Fahrzeuge im Bestand mit nur 18.000 km.',
    price: 41751,
    firstRegistration: '02/2025',
    km: 18000,
    powerKw: 140,
    powerPs: 190,
    fuel: 'Diesel',
    featured: true,
    photos: ['/api/vehicle-image/d2/d23be8a9-af0b-4464-b5f1-5961b178932d'],
  },
]

export const featuredVehicles = vehicles.filter((v) => v.featured)

export function getVehicleBySlug(slug: string) {
  return vehicles.find((v) => v.slug === slug)
}

export function formatPrice(price: number) {
  return price.toLocaleString('de-DE') + ' €'
}

export function formatKm(km: number) {
  return km.toLocaleString('de-DE') + ' km'
}
