/**
 * ECHTER FAHRZEUGBESTAND
 * ---------------------------------------------------------
 * Direkt von der echten AutoScout24-Händlerseite abgerufen:
 * https://www.autoscout24.de/haendler/autogalerie-keles
 * (20 von 36 Fahrzeugen — AutoScout24 lädt Seite 2 per
 * JavaScript nach, das kann mein Tool nicht mitklicken).
 *
 * Das ist die EINZIGE Quelle für Fahrzeugdaten auf der ganzen
 * Website (Startseite-Highlights + /fahrzeuge greifen beide
 * hier drauf zu). Sobald der Admin-Bereich steht, ersetzt eine
 * Datenbank diese Datei 1:1 — die Struktur bleibt gleich.
 *
 * TODO (Kunde):
 * - Fotos fehlen bei den meisten (siehe photo: null) — schickt
 *   mir Fotos oder pflegt sie später im Admin-Bereich ein.
 * - Die übrigen 16 Fahrzeuge (36 insgesamt) bitte nachreichen
 *   oder auf die Admin-Oberfläche warten.
 */

export type Vehicle = {
  id: number
  slug: string
  brand: string
  model: string
  detail: string
  description: string
  price: number
  priceNote?: string // z.B. "Fairer Preis", "Sehr guter Preis"
  firstRegistration: string // MM/JJJJ
  km: number
  powerKw: number
  powerPs: number
  fuel: 'Benzin' | 'Diesel' | 'Hybrid' | 'Elektro'
  transmission: 'Automatik' | 'Schaltgetriebe'
  owners: number
  consumption?: string
  emissions?: string
  featured: boolean
  photos: string[] // leer = noch kein echtes Foto vorhanden
}

export const vehicles: Vehicle[] = [
  {
    id: 1,
    slug: 'mercedes-benz-s-63-amg-coupe-4matic',
    brand: 'Mercedes-Benz',
    model: 'S 63 AMG Coupe 4Matic',
    detail: 'PANO · HUD · SITZBEL · SPUR · KEYLESS',
    description: 'Mercedes-Benz S 63 AMG Coupe 4Matic mit Panoramadach, Head-Up-Display, Sitzbelüftung, Spurhalteassistent und Keyless-Go.',
    price: 58751,
    priceNote: 'Fairer Preis',
    firstRegistration: '12/2014',
    km: 110000,
    powerKw: 430,
    powerPs: 585,
    fuel: 'Benzin',
    transmission: 'Automatik',
    owners: 2,
    consumption: '10,3 l/100 km (komb.)',
    emissions: '242 g/km (komb.)',
    featured: true,
    photos: [],
  },
  {
    id: 2,
    slug: 'mercedes-benz-c-63-amg',
    brand: 'Mercedes-Benz',
    model: 'C 63 AMG',
    detail: 'CARBON · PANO · HUD · SCHALENSITZE',
    description: 'Mercedes-Benz C 63 AMG mit Carbon-Paket, Panoramadach, Head-Up-Display und Schalensitzen.',
    price: 53651,
    priceNote: 'Fairer Preis',
    firstRegistration: '01/2020',
    km: 95000,
    powerKw: 350,
    powerPs: 476,
    fuel: 'Benzin',
    transmission: 'Automatik',
    owners: 2,
    consumption: '9,9 l/100 km (komb.)',
    emissions: '227 g/km (komb.)',
    featured: true,
    photos: [],
  },
  {
    id: 3,
    slug: 'mercedes-benz-gle-350-d-4matic-amg',
    brand: 'Mercedes-Benz',
    model: 'GLE 350 d 4Matic AMG',
    detail: 'PANO · 360° · HUD · MB100',
    description: 'Mercedes-Benz GLE 350 d 4Matic AMG-Line mit Panoramadach, 360°-Kamera, Head-Up-Display und MB100-Zertifizierung.',
    price: 51761,
    priceNote: 'Guter Preis',
    firstRegistration: '05/2020',
    km: 122000,
    powerKw: 200,
    powerPs: 272,
    fuel: 'Diesel',
    transmission: 'Automatik',
    owners: 2,
    consumption: '6,7 l/100 km (komb.)',
    emissions: '177 g/km (komb.)',
    featured: true,
    photos: [],
  },
  {
    id: 4,
    slug: 'bmw-420d-coupe',
    brand: 'BMW',
    model: '420d Coupe',
    detail: 'LED · NAVI · KAM · SPUR · SHZ · TEMPO',
    description: 'BMW 420d Coupe mit LED-Scheinwerfern, Navigation, Rückfahrkamera, Spurhalteassistent, Sitzheizung und Tempomat.',
    price: 43751,
    priceNote: 'Erhöhter Preis',
    firstRegistration: '02/2025',
    km: 18000,
    powerKw: 140,
    powerPs: 190,
    fuel: 'Diesel',
    transmission: 'Automatik',
    owners: 1,
    featured: true,
    photos: [],
  },
  {
    id: 5,
    slug: 'audi-sq7-4-0-tdi-quattro',
    brand: 'Audi',
    model: 'SQ7 4.0 TDI quattro',
    detail: 'STHZ · SPUR · SOFT · VIRTUAL',
    description: 'Audi SQ7 4.0 TDI quattro mit Standheizung, Spurhalteassistent, Soft-Close-Türen und Virtual Cockpit.',
    price: 38861,
    priceNote: 'Erhöhter Preis',
    firstRegistration: '11/2017',
    km: 161000,
    powerKw: 320,
    powerPs: 435,
    fuel: 'Diesel',
    transmission: 'Automatik',
    owners: 2,
    consumption: '7,6 l/100 km (komb.)',
    emissions: '199 g/km (komb.)',
    featured: true,
    photos: [],
  },
  {
    id: 6,
    slug: 'audi-a8-3-0-tdi-quattro-design-selection',
    brand: 'Audi',
    model: 'A8 3.0 TDI quattro design Selection',
    detail: 'HUD · GSD · 360°',
    description: 'Audi A8 3.0 TDI quattro design Selection mit Head-Up-Display, Geschwindigkeitsregelanlage und 360°-Kamera.',
    price: 21951,
    priceNote: 'Sehr guter Preis',
    firstRegistration: '09/2015',
    km: 190000,
    powerKw: 190,
    powerPs: 258,
    fuel: 'Diesel',
    transmission: 'Automatik',
    owners: 2,
    consumption: '5,9 l/100 km (komb.)',
    emissions: '156 g/km (komb.)',
    featured: true,
    photos: ['/images/car-audi-a8-real-temp.png'],
  },
  {
    id: 7,
    slug: 'vw-golf-viii-move-automatik',
    brand: 'Volkswagen',
    model: 'Golf VIII Lim. Move Autom.',
    detail: 'DIGITALT · KAM · LED · ACC',
    description: 'Volkswagen Golf VIII Limousine Move Automatik mit digitalem Tacho, Rückfahrkamera, LED-Licht und Abstandstempomat.',
    price: 23351,
    priceNote: 'Erhöhter Preis',
    firstRegistration: '07/2023',
    km: 92000,
    powerKw: 110,
    powerPs: 150,
    fuel: 'Diesel',
    transmission: 'Automatik',
    owners: 1,
    featured: false,
    photos: [],
  },
  {
    id: 8,
    slug: 'ford-mondeo-turnier-business-edition',
    brand: 'Ford',
    model: 'Mondeo Turnier Business Edition Autom.',
    detail: 'NAVI · SHZ',
    description: 'Ford Mondeo Turnier Business Edition Automatik mit Navigation und Sitzheizung.',
    price: 8651,
    priceNote: 'Fairer Preis',
    firstRegistration: '02/2017',
    km: 214000,
    powerKw: 110,
    powerPs: 150,
    fuel: 'Diesel',
    transmission: 'Automatik',
    owners: 3,
    consumption: '4,9 l/100 km (komb.)',
    emissions: '126 g/km (komb.)',
    featured: false,
    photos: [],
  },
  {
    id: 9,
    slug: 'vw-golf-vii-r-4motion',
    brand: 'Volkswagen',
    model: 'Golf VII R 4MOTION',
    detail: 'BEHINDERTENUMBAU · HANDGAS',
    description: 'Volkswagen Golf VII R 4MOTION mit Behindertenumbau und Handgas-Bedienung.',
    price: 27951,
    priceNote: 'Guter Preis',
    firstRegistration: '11/2017',
    km: 134000,
    powerKw: 280,
    powerPs: 381,
    fuel: 'Benzin',
    transmission: 'Automatik',
    owners: 1,
    consumption: '7,0 l/100 km (komb.)',
    emissions: '160 g/km (komb.)',
    featured: false,
    photos: [],
  },
  {
    id: 10,
    slug: 'vw-tiguan-highline-4motion',
    brand: 'Volkswagen',
    model: 'Tiguan Highline 4Motion',
    detail: 'PANO · SPUR · KAM · VIRTUAL · AHK',
    description: 'Volkswagen Tiguan Highline 4Motion mit Panoramadach, Spurhalteassistent, Kamera, Virtual Cockpit und Anhängerkupplung.',
    price: 20951,
    priceNote: 'Fairer Preis',
    firstRegistration: '12/2018',
    km: 149000,
    powerKw: 110,
    powerPs: 150,
    fuel: 'Diesel',
    transmission: 'Automatik',
    owners: 1,
    consumption: '6,9 l/100 km (komb.)',
    emissions: '155 g/km (komb.)',
    featured: false,
    photos: [],
  },
  {
    id: 11,
    slug: 'vw-golf-vii-comfortline',
    brand: 'Volkswagen',
    model: 'Golf VII Lim. Comfortline',
    detail: 'LEDER · KLIMAAUT · SHZ · PDC',
    description: 'Volkswagen Golf VII Limousine Comfortline mit Lederausstattung, Klimaautomatik, Sitzheizung und Parkdistanzkontrolle.',
    price: 8251,
    priceNote: 'Fairer Preis',
    firstRegistration: '01/2013',
    km: 140000,
    powerKw: 63,
    powerPs: 86,
    fuel: 'Benzin',
    transmission: 'Schaltgetriebe',
    owners: 2,
    consumption: '4,9 l/100 km (komb.)',
    emissions: '113 g/km (komb.)',
    featured: false,
    photos: [],
  },
  {
    id: 12,
    slug: 'audi-a4-avant-40-tdi-s-line',
    brand: 'Audi',
    model: 'A4 Avant 40 TDI S line',
    detail: 'DIGIT · AHK · RFK · SHZ',
    description: 'Audi A4 Avant 40 TDI S line mit digitalem Tacho, Anhängerkupplung, Rückfahrkamera und Sitzheizung.',
    price: 26841,
    priceNote: 'Erhöhter Preis',
    firstRegistration: '01/2023',
    km: 111000,
    powerKw: 150,
    powerPs: 204,
    fuel: 'Diesel',
    transmission: 'Automatik',
    owners: 1,
    consumption: '4,7 l/100 km (komb.)',
    emissions: '123 g/km (komb.)',
    featured: false,
    photos: [],
  },
  {
    id: 13,
    slug: 'vw-passat-comfortline-dsg',
    brand: 'Volkswagen',
    model: 'Passat Lim. Comfortline DSG',
    detail: 'KLIMA · PDC · TEMPO',
    description: 'Volkswagen Passat Limousine Comfortline DSG mit Klimaanlage, Parkdistanzkontrolle und Tempomat.',
    price: 10751,
    priceNote: 'Fairer Preis',
    firstRegistration: '09/2013',
    km: 175000,
    powerKw: 155,
    powerPs: 211,
    fuel: 'Benzin',
    transmission: 'Automatik',
    owners: 2,
    consumption: '7,7 l/100 km (komb.)',
    emissions: '180 g/km (komb.)',
    featured: false,
    photos: [],
  },
  {
    id: 14,
    slug: 'mercedes-vito-kasten',
    brand: 'Mercedes-Benz',
    model: 'Vito Kasten 109/110/111/114 CDI FWD lang',
    detail: 'KLIMA',
    description: 'Mercedes-Benz Vito Kasten FWD lang mit Klimaanlage.',
    price: 12731,
    priceNote: 'Fairer Preis',
    firstRegistration: '03/2017',
    km: 150000,
    powerKw: 84,
    powerPs: 114,
    fuel: 'Diesel',
    transmission: 'Schaltgetriebe',
    owners: 1,
    consumption: '6,3 l/100 km (komb.)',
    emissions: '164 g/km (komb.)',
    featured: false,
    photos: [],
  },
  {
    id: 15,
    slug: 'fiat-500c-cabrio',
    brand: 'Fiat',
    model: '500C Cabrio',
    detail: 'KLIMA · PDC · EURO 6',
    description: 'Fiat 500C Cabrio mit Klimaanlage, Parkdistanzkontrolle und Euro-6-Norm.',
    price: 7951,
    priceNote: 'Guter Preis',
    firstRegistration: '09/2014',
    km: 46000,
    powerKw: 51,
    powerPs: 69,
    fuel: 'Benzin',
    transmission: 'Schaltgetriebe',
    owners: 1,
    consumption: '5,1 l/100 km (komb.)',
    emissions: '121 g/km (komb.)',
    featured: false,
    photos: [],
  },
  {
    id: 16,
    slug: 'mazda-cx-3-sports-line',
    brand: 'Mazda',
    model: 'CX-3 Sports-Line',
    detail: 'LEDER · NAVI · XEN · HUD · SPUR · KAM · TOT',
    description: 'Mazda CX-3 Sports-Line mit Lederausstattung, Navigation, Xenonlicht, Head-Up-Display, Spurhalte- und Totwinkelassistent.',
    price: 18951,
    priceNote: 'Fairer Preis',
    firstRegistration: '02/2019',
    km: 9500,
    powerKw: 89,
    powerPs: 121,
    fuel: 'Benzin',
    transmission: 'Schaltgetriebe',
    owners: 1,
    consumption: '6,2 l/100 km (komb.)',
    emissions: '141 g/km (komb.)',
    featured: false,
    photos: [],
  },
  {
    id: 17,
    slug: 'vw-touran-comfortline',
    brand: 'Volkswagen',
    model: 'Touran Comfortline',
    detail: 'SHZ · PDC · TEMP · EURO5',
    description: 'Volkswagen Touran Comfortline mit Sitzheizung, Parkdistanzkontrolle, Tempomat und Euro-5-Norm.',
    price: 8251,
    priceNote: 'Fairer Preis',
    firstRegistration: '11/2011',
    km: 166000,
    powerKw: 77,
    powerPs: 105,
    fuel: 'Diesel',
    transmission: 'Schaltgetriebe',
    owners: 1,
    consumption: '5,1 l/100 km (komb.)',
    emissions: '134 g/km (komb.)',
    featured: false,
    photos: [],
  },
  {
    id: 18,
    slug: 'mitsubishi-pajero-3-2-di-d-top',
    brand: 'Mitsubishi',
    model: 'Pajero 3.2 DI-D Top',
    detail: 'RFK · 7-SITZ · ALLRAD · 3,5T · PANO',
    description: 'Mitsubishi Pajero 3.2 DI-D Top mit Rückfahrkamera, 7 Sitzen, Allradantrieb, 3,5t Anhängelast und Panoramadach.',
    price: 25651,
    priceNote: 'Sehr guter Preis',
    firstRegistration: '01/2016',
    km: 144000,
    powerKw: 140,
    powerPs: 190,
    fuel: 'Diesel',
    transmission: 'Automatik',
    owners: 1,
    consumption: '9,3 l/100 km (komb.)',
    emissions: '246 g/km (komb.)',
    featured: false,
    photos: [],
  },
]

export const featuredVehicles = vehicles.filter((v) => v.featured)

export function getVehicleBySlug(slug: string) {
  return vehicles.find((v) => v.slug === slug)
}

export function formatPrice(price: number) {
  return price.toLocaleString('de-DE') + ' €'
}

export function formatKm(km: number) {
  return km.toLocaleString('de-DE') + ' km'
}
